# --- General options --- #

# Name of website
title: Akira

# Short description of your site
description: Kono Dio Da !!! 

markdown: kramdown
#remote_theme: pmarsceill/just-the-docs

theme: jekyll-theme-hacker
